### Άσκηση 1

Γράψτε ένα προγραμματάκι που θα αθροίζει όλους τους περιττούς αριθμούς από το 1 έως και το 100 και θα τυπώνει το τελικό άθροισμα.

Hints & tips:

- περιττοί είναι οι αριθμοί που το υπόλοιπο της διαίρεσής τους με το 2 ΔΕΝ είναι 0 (x % 2 != 0)
- μπορούμε αρχικά να ορίσουμε ότι το άθροισμα των περιττών αριθμών είναι 0 (sum = 0)
- στη συνέχεια μπορούμε να φτιάξουμε μια λούπα που θα κάνει τα εξής:
  - για κάθε αριθμό από το 1 ως και το 100
  - αν το υπόλοιπο της διαίρεσης του αριθμού με το 2 δεν είναι 0
  - το άθροισμα θα αυξάνεται κατά τον αριθμό

In [1]:
sum_odds = 0

for x in range(1, 101):
    if x % 2 != 0:
        sum_odds += x

print("Άθροισμα περιττών:", sum_odds)

Άθροισμα περιττών: 2500



---

### Άσκηση 2

Τροποποιήστε το παραπάνω πρόγραμμα έτσι ώστε, εκτός από το άθροισμα των περιττών, να υπολογίζει και να τυπώνει ΚΑΙ:
- το πλήθος των περιττών αριθμών
- το άθροισμα των ζυγών αριθμών στο ίδιο εύρος
- το πλήθος των ζυγών αριθμών

In [2]:
sum_odds = 0
count_odds = 0
sum_evens = 0
count_evens = 0

for x in range(1, 101):
    if x % 2 != 0:
        sum_odds += x
        count_odds += 1
    else:
        sum_evens += x
        count_evens += 1

print("Άθροισμα περιττών:", sum_odds)
print("Πλήθος περιττών:", count_odds)
print("Άθροισμα ζυγών:", sum_evens)
print("Πλήθος ζυγών:", count_evens)

Άθροισμα περιττών: 2500
Πλήθος περιττών: 50
Άθροισμα ζυγών: 2550
Πλήθος ζυγών: 50



---

### Άσκηση 3

Αντιγράψτε εδώ τον κώδικα που γράψατε για την 1η Άσκηση του notebook "exercise3.ipynb".

Θα χρειαστούμε τη λίστα με τα λεξικά των άρθρων.

Χρησιμοποιώντας τη βιβλιοθήκη Pandas, φτιάξτε ένα dataframe με τα δεδομένα της λίστας με τα λεξικά των άρθρων.
Στη συνέχεια, εμφανίστε το dataframe στην οθόνη.

**Hints & tips**:
- για να χρησιμοποιήσετε τη βιβλιοθήκη pandas πρέπει πρώτα να την εισάγετε: import pandas as pd
- η δημιουργία ενός dataframe από μια λίστα με λεξικά, γίνεται με την εξής σύνταξη: df = pd.DataFrame(<όνομα λίστας με λεξικά>)

In [3]:

# Δημιουργία κενής λίστας για αποθήκευση δεδομένων άρθρων
articles = []

# Δημιουργία λεξικού για το πρώτο άρθρο
article1 = {
    "Τίτλος": "Πρώτο Άρθρο",
    "Ημερομηνία": "2025-03-18",
    "Κατηγορία": "Τεχνολογία",
    "url": "https://example.com/article1"
}

# Δημιουργία λεξικού για το δεύτερο άρθρο
article2 = {
    "Τίτλος": "Δεύτερο Άρθρο",
    "Ημερομηνία": "2025-03-17",
    "Κατηγορία": "Επιστήμη",
    "url": "https://example.com/article2"
}

# Προσθήκη των λεξικών στη λίστα
articles.append(article1)
articles.append(article2)

# Τύπωμα του τίτλου του δεύτερου άρθρου
print(articles[1]["Τίτλος"])

# Προσθήκη εγγραφής με το όνομα του site
articles[0]["site"] = "example.com"
articles[1]["site"] = "example.com"

# Τύπωμα του πλήθους των λεξικών στη λίστα
print(len(articles))

Δεύτερο Άρθρο
2

In [4]:
import pandas as pd

In [5]:
# Η λίστα articles από το exercise3.ipynb
articles = []

article1 = {
    "Τίτλος": "Πρώτο Άρθρο",
    "Ημερομηνία": "2025-03-18",
    "Κατηγορία": "Τεχνολογία",
    "url": "https://example.com/article1",
    "site": "example.com"
}

article2 = {
    "Τίτλος": "Δεύτερο Άρθρο",
    "Ημερομηνία": "2025-03-17",
    "Κατηγορία": "Επιστήμη",
    "url": "https://example.com/article2",
    "site": "example.com"
}

articles.append(article1)
articles.append(article2)

# Δημιουργία dataframe
df = pd.DataFrame(articles)

# Εμφάνιση dataframe
df

,Τίτλος,Ημερομηνία,Κατηγορία,url,site
0,Πρώτο Άρθρο,2025-03-18,Τεχνολογία,https://example.com/article1,example.com
1,Δεύτερο Άρθρο,2025-03-17,Επιστήμη,https://example.com/article2,example.com



---

### Άσκηση 4 (intro)

Στο site "ourworldindata.org" παρέχονται πάρα πολλά δεδομένα και γραφήματα για διάφορα topics για όλες τις χώρες του κόσμου.

Για παράδειγμα, στη σελίδα https://ourworldindata.org/explorers/covid?Metric=Excess+mortality+%28estimates%29&Interval=Cumulative&Relative+to+population=false&country=USA~BRA~JPN~DEU, παρέχονται δεδομένα και γραφήματα σχετικά με την Covid-19.

Αν επισκεφθείτε την παραπάνω σελίδα, επάνω αριστερά, υπάρχει ένας υπερσύνδεσμος με το κείμενο "Download this dataset". Εάν τον πατήσετε θα οδηγηθείτε στη σελίδα με τα datasets για τον covid.

Πιο κάτω, σ' αυτή τη σελίδα, υπάρχει η ενότητα "Download data", με πολλά κουμπάκια download.

Όταν πατήσετε κάποιο download μεταφέρεστε στη σελίδα του raw αρχείου csv με τα δεδομένα.

Μπορούμε να φέρουμε αυτά τα δεδομένα σε ένα dataframe στην Python, με την παρακάτω εντολή:

In [ ]:
covid_df = pd.read_csv("https://catalog.ourworldindata.org/garden/covid/latest/cases_deaths/cases_deaths.csv")
covid_df

,country,date,new_cases,total_cases,new_deaths,total_deaths,weekly_cases,weekly_deaths,weekly_pct_growth_cases,weekly_pct_growth_deaths,...,cfr_100_cases,cfr_short_term,days_since_100_total_cases,days_since_5_total_deaths,days_since_1_total_cases_per_million,days_since_0_1_total_deaths_per_million,days_since_100_total_cases_and_5m_pop,total_deaths_last12m,total_deaths_per_100k_last12m,total_deaths_per_million_last12m
0,Afghanistan,2020-01-04,0.0,0,0.0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,-86.0,-91.0,-81.0,-91.0,-86.0,NaN,NaN,NaN
1,Afghanistan,2020-01-05,0.0,0,0.0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,-85.0,-90.0,-80.0,-90.0,-85.0,NaN,NaN,NaN
2,Afghanistan,2020-01-06,0.0,0,0.0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,-84.0,-89.0,-79.0,-89.0,-84.0,NaN,NaN,NaN
3,Afghanistan,2020-01-07,0.0,0,0.0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,-83.0,-88.0,-78.0,-88.0,-83.0,NaN,NaN,NaN
4,Afghanistan,2020-01-08,0.0,0,0.0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,-82.0,-87.0,-77.0,-87.0,-82.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471245,Zimbabwe,2025-02-26,0.0,266410,0.0,5740,0.0,0.0,NaN,NaN,...,2.154574,NaN,1737.0,1819.0,1779.0,1819.0,1737.0,0.0,0.0,0.0
471246,Zimbabwe,2025-02-27,0.0,266410,0.0,5740,0.0,0.0,NaN,NaN,...,2.154574,NaN,1738.0,1820.0,1780.0,1820.0,1738.0,0.0,0.0,0.0
471247,Zimbabwe,2025-02-28,0.0,266410,0.0,5740,0.0,0.0,NaN,NaN,...,2.154574,NaN,1739.0,1821.0,1781.0,1821.0,1739.0,0.0,0.0,0.0
471248,Zimbabwe,2025-03-01,0.0,266410,0.0,5740,0.0,0.0,NaN,NaN,...,2.154574,NaN,1740.0,1822.0,1782.0,1822.0,1740.0,0.0,0.0,0.0
471249,Zimbabwe,2025-03-02,0.0,266410,0.0,5740,0.0,0.0,NaN,NaN,...,2.154574,NaN,1741.0,1823.0,1783.0,1823.0,1741.0,0.0,0.0,0.0



---

### Άσκηση 4 (actual part)

Βρείτε από το ourworldindata.org ένα dataset που σας ενδιαφέρει και ανοίξτε το σαν dataframe.

In [23]:
co2_df = pd.read_csv("https://ourworldindata.org/grapher/aviation-share-co2.csv?v=1&csvType=full&useColumnShortNames=true")

In [24]:
print((co2_df))

   entity      code  year  aviation_share_total_co2
0   World  OWID_WRL  1940                      0.32
1   World  OWID_WRL  1941                      0.33
2   World  OWID_WRL  1942                      0.36
3   World  OWID_WRL  1943                      0.39
4   World  OWID_WRL  1944                      0.41
..    ...       ...   ...                       ...
77  World  OWID_WRL  2017                      2.39
78  World  OWID_WRL  2018                      2.46
79  World  OWID_WRL  2019                      2.47
80  World  OWID_WRL  2020                      1.55
81  World  OWID_WRL  2021                      1.77

[82 rows x 4 columns]

In [25]:
co2_df

   entity      code  year  aviation_share_total_co2
0   World  OWID_WRL  1940                      0.32
1   World  OWID_WRL  1941                      0.33
2   World  OWID_WRL  1942                      0.36
3   World  OWID_WRL  1943                      0.39
4   World  OWID_WRL  1944                      0.41
..    ...       ...   ...                       ...
77  World  OWID_WRL  2017                      2.39
78  World  OWID_WRL  2018                      2.46
79  World  OWID_WRL  2019                      2.47
80  World  OWID_WRL  2020                      1.55
81  World  OWID_WRL  2021                      1.77

[82 rows x 4 columns]